### ISSUE TITLE
Completed Week 3 Assignment

### ISSUE THREAD

**Issue by nvh0412** [nvh0412/CoderTicket#2]
Here is my completed assignment of week 3, thanks!
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Ruby submission, nvh0412!

 :smiley: Everything looks good with the format of your submission. We'll be providing a detailed review soon!

**Comment by chug2k** [comment]
Sorry for the late review. :sweat_smile: Thanks for your work on the CoderTicket Assignment! :ticket:. This was the “final boss” of homework assignments - seeing if you can build a whole, end-to-end web application. There are complex dependent relationships (such as ticket / ticket_type / event) and we also asked you to write unit tests. Thanks for your hard work!

## Notes
- Hmm, not as good as your previous work, Hoa. :confused: It seems to crash a lot when I look at it on Heroku...but you did a good job with the tests! :grinning: 
- Great job with adding the `up_comming` method to `Event`. Try to keep your controllers short. 
- Good use of `respond_with`. 
- Good job with the `save_ticket` method! There are a few ways you could improve this though. The first is that you should validate that the ticket can actually save (`ticket_type.max_quantity` should not be less than 0.) You can do this with a custom validator method on ticket. You can also do a `before_create` callback to adjust the `ticket_type.max_quantity` as well, although what you did was also fine. (@harley is not a big proponent of the `before/after_xxx` callbacks.) I like it here though, because if you call .save_ticket multiple times, you will keep decreasing the `max_quantity`, which is a major bug! :bug:
- HAML is great, isn't it? I I'm telling ya...try give slim a chance. 

## Tests

Great job on the tests, and the handy FactoryGirl functions like `create_list`. Fancy stuff with the `up_comming` trait, as well.
- My main suggestion here is that model tests are probably the most useful of all tests. Once you figure out how to easily create instances for testing (such as with Factory Girl) you should be writing _mostly_ model tests. This is one reason it's good to keep logic in the model - it becomes much easier to unit test.
